{% set name = "pycryptodome" %}
{% set version = "3.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 09609209ed7de61c2b560cc5c8c4fbf892f8b15b1faf7e4cbffac97db1fffda7
  patches:
    - 0001-Make-load_lib-CONDA_PREFIX-aware.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --no-build-isolation
  ignore_run_exports:
    - gmp  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - m2-patch  # [win]
    - patch  # [not win]
    - git    # [not win]
  host:
    - pip
    - python
    - gmp   # [not win]
    - setuptools
    - wheel
  run:
    - python
    - gmp   # [not win]

test:
  requires:
    - pytest
    - pip
  commands:
    - pip check
  imports:
    - Crypto
    - Crypto.Cipher
    - Crypto.Hash
    - Crypto.IO
    - Crypto.Math
    - Crypto.Protocol
    - Crypto.PublicKey
    - Crypto.Random
    - Crypto.SelfTest
    - Crypto.SelfTest.Cipher
    - Crypto.SelfTest.Hash
    - Crypto.SelfTest.IO
    - Crypto.SelfTest.Math
    - Crypto.SelfTest.Protocol
    - Crypto.SelfTest.PublicKey
    - Crypto.SelfTest.Random
    - Crypto.SelfTest.Signature
    - Crypto.SelfTest.Util
    - Crypto.Signature
    - Crypto.Util

about:
  home: https://www.pycryptodome.org
  license: BSD-2-Clause AND Unlicense
  license_family: BSD
  license_file: LICENSE.rst
  summary: Cryptographic library for Python
  description: |
    PyCryptodome is a self-contained Python package of low-level cryptographic primitives. PyCryptodome is not a wrapper to a separate C library like OpenSSL. To the largest possible extent, algorithms are implemented in pure Python. Only the pieces that are extremely critical to performance (e.g. block ciphers) are implemented as C extensions.
  doc_url: https://www.pycryptodome.org/en/latest/
  dev_url: https://github.com/Legrandin/pycryptodome

extra:
  recipe-maintainers:
    - mariusvniekerk
